In [1]:
using Interpolations
using NPZ

In [2]:
psi = npzread("/net/scratch4/giannis_kx/pixie3d/iter/int_kink/11/11_new_visc.scratch/psi.npy");

In [8]:
psig = npzread("/net/scratch4/giannis_kx/pixie3d/iter/int_kink/11/11_new_visc.scratch/psi_grid.npy");

In [11]:
size(psig)

(128, 65, 33, 1)

In [23]:
function dAdr(arr,theta,fi,t)
    dr = 1.0 / size(arr,1)
    psi = arr[:,theta,fi,t]
    psiplus = circshift(psi,(-1))
    psiminus = circshift(psi,(1))
    dpsidr = (psiplus - psiminus)/(2.0*dr)
    dpsidr_start = (psi[2]-psi[1])/dr
    dpsidr_end = (psi[length(psi)]-psi[length(psi)-1])/dr
    dpsidr[1] = dpsidr_start
    dpsidr[length(psi)] = dpsidr_end
    return dpsidr
end

dAdr (generic function with 2 methods)

In [55]:
function deriv(arr)
    t_deriv = [] 
    for theta in range(1,stop=size(arr,2))
        for fi in range(1,stop=size(arr,3))
            t_deriv = append!(t_deriv,dAdr(arr,theta,fi,1))
        end
    end
    return permutedims(reshape(t_deriv,(size(arr,1),size(arr,3),size(arr,2))),(1,3,2))
end

deriv (generic function with 1 method)

In [63]:
function dAdt(arr,r,fi,t)
    dtheta = 2.0*pi / size(arr,2)
    psi = arr[r,:,fi,t]
    psiplus = circshift(psi,(-1))
    psiminus = circshift(psi,(1))
    dpsidtheta = (psiplus - psiminus)/(2.0*dtheta)
    dpsidtheta_start = (psi[2]-psi[1])/dtheta
    dpsidtheta_end = (psi[length(psi)]-psi[length(psi)-1])/dtheta
    dpsidtheta[1] = dpsidtheta_start
    dpsidtheta[length(psi)] = dpsidtheta_end
    return dpsidtheta
end

dAdt (generic function with 1 method)

In [82]:
function deriv_t(arr)
    t_deriv = [] 
    for r in range(1,stop=size(arr,1))
        for fi in range(1,stop=size(arr,3))
            t_deriv = append!(t_deriv,dAdt(arr,r,fi,1))
        end
    end
    return permutedims(reshape(t_deriv,(size(arr,2),size(arr,3),size(arr,1))),(3,1,2))
end

deriv_t (generic function with 1 method)

In [83]:
temp3 = deriv_t(psig)

128×65×33 Array{Any,3}:
[:, :, 1] =
 -0.00648774  -0.00594653   -0.00528775   …  -0.00756698   -0.00762529
 -0.00046261  -0.000489439  -0.000475767     -0.000695309  -0.000663293
 -0.00103665  -0.00107713   -0.00102246      -0.00154287   -0.00146634
 -0.0016037   -0.00164947   -0.00153666      -0.00241219   -0.00228236
 -0.00216287  -0.00220537   -0.00201685      -0.0033025    -0.00311057
 -0.00271318  -0.0027436    -0.0024615    …  -0.00421282   -0.00394993
 -0.0032535   -0.0032629    -0.00286906      -0.00514194   -0.00479925
 -0.00378274  -0.003762     -0.00323812      -0.00608861   -0.00565724
 -0.00429981  -0.00423973   -0.00356745      -0.00705159   -0.00652266
 -0.00480377  -0.0046951    -0.00385612      -0.00802976   -0.00739436
 -0.00529387  -0.00512734   -0.00410345   …  -0.00902226   -0.0082714
 -0.00576956  -0.00553593   -0.00430916      -0.0100285    -0.00915316
 -0.00623058  -0.00592069   -0.00447328      -0.0110485    -0.0100394
  ⋮                                       

In [84]:
temp3[17,18,19]

0.009550812969875904

In [84]:
m = @which dAdr(psi,1,1,1)

dAdr(arr, r, theta, t) in Main at In[61]:1

In [85]:
Base.delete_method(m)

In [33]:
tmp1=circshift(psi,(0,-1,0,0));

In [34]:
tmp1[1,1,1,1]

0.207716013539018

In [35]:
tmp1=[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [37]:
push!(tmp1,10)

4-element Array{Int64,1}:
  1
  2
  3
 10

In [38]:
append!([10],tmp1)

5-element Array{Int64,1}:
 10
  1
  2
  3
 10

In [18]:
j = []
i=-6
while size(j)[1]<4
    try 
        append!(j,sqrt(i))
    catch 
        try
            i = i+1
            append!(j,sqrt(i))
        catch
        end
    end
    i = i+1
    println(j)
end

Any[]
Any[]
Any[]
Any[0.0]
Any[0.0, 1.0]
Any[0.0, 1.0, 1.4142135623730951]
Any[0.0, 1.0, 1.4142135623730951, 1.7320508075688772]


In [15]:
j=[]
size(j)[1]

0